FROM ceph/ceph:v15.2 AS base
RUN curl -sL https://rpm.nodesource.com/setup_12.x | bash -
RUN yum install -y nodejs
RUN yum clean packages && yum clean metadata && yum clean all && rm -rf /var/cache/dnf

FROM base AS builder
COPY . /app
WORKDIR /app
RUN npm install
RUN npx tsc

FROM base
LABEL maintainer="Rob Kaandorp <rob@di.nl>"
COPY --from=builder /app /app
WORKDIR /app
RUN mkdir -p /run/docker/plugins /mnt/state /mnt/volumes /etc/ceph
COPY test/rbd.sh /usr/bin/rbd
RUN chmod +x /usr/bin/rbd
CMD ["node", "./node_modules/testyts/build/testy.js"]